name: Hardcoded API Key Demo

on:
  push:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hardcode API Key
        run: |
          echo "Using Hardcode API Key: 12345-SECRET-KEY"
  
